### ISSUE TITLE
What do I need to configure if I want to use this library in an embedded device? such as stm32

### ISSUE THREAD

**Issue by Darwinnpos** [niXman/yas#131]
What do I need to configure if I want to use this library in an embedded device? such as stm32

**Comment by niXman** [comment]
you can look at `yas::compacted` option.
it allows integrals to be packed into byte arrays as small as possible without loss of value.
you can see it there:
https://github.com/niXman/yas/blob/master/include/yas/detail/io/binary_streams.hpp#L81
https://github.com/niXman/yas/blob/master/include/yas/detail/io/binary_streams.hpp#L118

and a few words according disabling YAS header bytes: I think it's a bad idea because it deprives the deserializer of the first-level protection from some data-noise/garbage/wrong-data.

moreover, the header carries useful information: https://github.com/niXman/yas/blob/master/include/yas/detail/io/header.hpp#L56

the header is only seven bytes long. and I don't consider this to be significant.

**Comment by Darwinnpos** [comment]
How should I configure this file if I use stm32？
(https://github.com/niXman/yas/tree/master/include/yas/detail/config)/endian.hpp

**Comment by niXman** [comment]
@Darwinnpos nothing else needs to be configured.

@daldegam YAS by default uses the architecture provided by the host.

**Comment by niXman** [comment]
@Darwinnpos please close the issue if you have no other questions.
